config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  devise_for :users
  get 'main', to: 'main#index', as: 'main_index'
  resources :guides
  resources :bookings
  get 'guides/:guide_id/bookings/new', to: 'bookings#new', as: 'new_guide_booking'
  delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
  get '/reviews/new', to: 'reviews#new', as: 'new_review'
  post '/reviews/', to: 'reviews#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guide
  belongs_to :user

  def self.create_booking(date, guide_id, user_id)
    booking = Booking.new(date: date, guide_id: guide_id, user_id: user_id)
    if booking.save == false
      logger.info booking.errors.inspect
    end
    return booking
  end
end

app/models/guide.rb
class Guide < ApplicationRecord
    has_many :bookings
    has_many :reviews

    def self.create_guide(name, phone_number, city, country, cost)
        guide = Guide.new(name: name, phone_number: phone_number, city: city, country: country, cost: cost)
        guide.save
        return guide
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :guide
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number, :name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :name])
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new
    end

    def create
        @booking = Booking.create_booking(params[:booking][:date], params[:booking][:guide_id], current_user.id)
        logger.info current_user.inspect
        redirect_to bookings_path
    end

    def index
        @bookings = current_user.bookings.order(:date)
    end

    def edit
        @booking = current_user.bookings.find(params[:id])
    end

    def update
        @booking = Booking.find(params[:id])
        booking_params = params.require(:booking).permit(:date)
        if @booking.update(booking_params)
            redirect_to bookings_path
        else
            render 'new'
        end
    end

    def show
        @booking = Booking.find(params[:id])
    end

    def destroy
        @booking = Booking.find(params[:id])
        @booking.destroy
        redirect_to bookings_path
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
    def index
        @bookings = current_user.bookings.order(:id)
    end
    
    def show
        @guide = Guide.find(params[:id])
        @reviews = @guide.reviews
    end

    def new
        @guide = Guide.new
    end

    def create
        @guide = Guide.create_guide(params[:guide][:name], params[:guide][:phone_number], params[:guide][:city], params[:guide][:country], params[:guide][:cost])
        redirect_to main_index_path
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if user_signed_in?
      return redirect_to main_index_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @guides = Guide.all.order(:country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
        @review.guide_id = params[:guide]
    end

    def create
        guide = Guide.find(params[:review][:guide_id])
        @review = guide.reviews.new
        @review.user_id = current_user.id
        @review.comment = params[:review][:comment]
        if @review.save
            redirect_to guide_path(guide)
        else
            flash[:alert] = "Oops. There was a problem creating the review."
        end
    end     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/guide_helper.rb
module GuideHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/main_helper.rb
module MainHelper
    def emoji_flag_for_country(country)
        ISO3166::Country.find_country_by_name(country).emoji_flag
    end

    def country_code(country)
        ISO3166::Country.find_country_by_name(country).country_code
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/traveller_helper.rb
module TravellerHelper
end

app/views/bookings/edit.html.erb
<h1 class='title'><%= "Your booking with #{@booking.guide.name}" %></h1>

<%= form_with model: @booking, local:true do |form| %>
    <%= form.hidden_field :guide_id, value: params[:guide_id] %>
    <div class="field">
        <%=label(:date, 'Date', :class => 'label')%>
        <div class="control">
            <%= form.date_field :date, required: true, :class => 'input'%>
        </div>
    </div>
    <br>
    <p><%= form.submit "Update", :class => 'button is-primary' %></p>
    <br>
    <p><%= link_to("Back", main_index_path, :method => :get, :class => 'button is-primary') %></p>
<%end%>

app/views/bookings/index.html.erb
<div>
<h1 class="title">My Bookings</h1>
<table class="table is-striped">
  <thead>  
    <tr>
        <th>Booking Date</th>
        <th>Tour Guide</th>
    </tr>
  </thead>
  <tbody>
    <%if @bookings%>
      <% @bookings.each do |i| %>
        <tr>
            <td><%=i.date%></td>
            <td><%=link_to i.guide.name, guide_path(i) %></td>
            <td><%=link_to 'Edit', edit_booking_path(i)%></td>
            <td><%= link_to 'Delete', delete_booking_path(i.id), :method => :delete %></td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
 </table>
  <p><%= link_to("Back", main_index_path, :method => :get, :class => 'button is-primary') %></p>
</div>

app/views/bookings/new.html.erb
<%= form_with model: @booking, local:true do |form| %>
    <%= form.hidden_field :guide_id, value: params[:guide_id] %>
    <div class="field">
        <%=label(:date, 'Date', :class => 'label')%>
        <div class="control">
            <%= form.date_field :date, required: true, :class => 'input'%>
        </div>
    </div>
    <br>
    <p><%= form.submit "Add Booking", :class => 'button is-primary' %></p>
    <br>
    <p><%= link_to("Back", main_index_path, :method => :get, :class => 'button is-primary') %></p>
<%end%>

app/views/guides/new.html.erb
<h1 class="title">Join as a Guide</h1>
<%= form_with model: @guide, local:true do |form| %>
    <div class="field">
        <%=label(:name, 'Name', :class => 'label')%>
        <div class="control">
            <%= form.text_field :name, required: true, minlength: 1, :class => 'input', :type => 'text', :placeholder => 'Name'%>
        </div>
    </div>
    <div class="field">
        <%=label(:phone_number, 'Phone Number', :class => 'label')%>
        <div class="control has-icons-left has-icons-right">
            <%= form.text_field :phone_number, required: true, :class => 'input', :placeholder => 'Phone Number', :type => 'tel'%>
            <span class="icon is-small is-left">
            <i class="fas fa-phone"></i>
            </span>
        </div>
    </div>
    <div class="field">
        <%=label(:city, 'City', :class => 'label')%>
        <div class="control has-icons-left has-icons-right">
            <%= form.text_field :city, required: true, minlength: 1, :class => 'input', :placeholder => 'City', :type => 'text' %>
            <span class="icon is-small is-left">
            <i class="fas fa-city"></i>
            </span>
        </div>
    </div>
    <div class="field">
    <%=label(:country, 'Country', :class => 'label')%>
        <p class="control select">
            <%= form.collection_select(:country, ISO3166::Country.countries.sort_by(&:name).collect { |c| [ c.name, "#{c.name} #{c.emoji_flag}" ] }, :first, :last, {include_blank: 'Select a country'}, 'data-style': 'form-control', required: true) %>
        </p>
    </div>
    <div class="field">
        <%=label(:cost, 'Price', :class => 'label')%>
        <div class="control has-icons-left has-icons-right">
            <%= form.number_field :cost, required: true, minlength: 1, :class => 'input', :placeholder => 'Price' %>
            <span class="icon is-small is-left">
            <i class="fas fa-dollar-sign"></i>
            </span>
        </div>
    </div>
    <br>
    <p><%= form.submit "Add details", :class => 'button is-primary' %></p><br>
    <p><%= link_to("Back", main_index_path, :method => :get, :class => 'button is-primary') %></p>
<%end%>

app/views/guides/show.html.erb
<h1 class='title is-1'><%=@guide.name %><%= " #{emoji_flag_for_country(@guide.country)}" %></h1>

<table class="table is-hoverable">
  <tbody>
    <tr>
      <th>Phone Number</th>
      <td><%= "#{number_to_phone(@guide.phone_number, country_code: country_code(@guide.country), delimiter: " ")}" %></td>
    </tr>
    <tr>
      <th>City</th>
      <td><%= "#{@guide.city}" %></td>
    </tr>
    <tr>
      <th>Country</th>
      <td><%= "#{@guide.country}" %></td>
      <td></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= "$#{@guide.cost}" %></td>
    </tr>
  </tbody>
</table>
<p><%= link_to "Book", new_guide_booking_path(guide_id: @guide.id), :class => "button is-warning"%></p>
<br>
<p><%= link_to 'Add a review', new_review_path(guide: @guide), :class => "button is-link" %></p><br>
<div>
  <h4 class="is-size-3">Reviews</h4>
  <div class="card">
  <% if @reviews %>
    <% @reviews.each do |review| %>
      <header class="card-header">
        <p class="card-header-title">
        <%= review.user.name %>
        </p>
      </header>
      <div class="card-content">
        <div class="content">
          <%= review.comment%>
        </div>
      </div>
    <%end%>
  <%end%>
</div>
</div>
<br>
<p><%= link_to "Back", main_index_path, :class => "button is-primary"%></p>

app/views/homepage/index.html.erb
<h1 class="title">Guidefully</h1>
<h2 class="subtitle">Connecting you with local guides<h2>
<%= image_tag("adventure-blur-cartography-408503.jpg", :alt => "Guide") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guidefully</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="section">
    <%= render "shared/topnav" %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>    
    <br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div>
  <%= button_to 'View my Tour Bookings', bookings_path, :method => :get, :class => 'button is-info'%>
  <br>
</div>
<div>
  <table class="table is-striped">
    <thead>  
      <tr>
        <th>Tour Guide Name</th>
        <th>Phone Number</th>
        <th>City</th>
        <th>Country</th>
        <th></th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <%if @guides%>
        <% @guides.each do |i| %>
          <tr>
            <td><%=link_to i.name, guide_path(i) %></td>
            <td><%= number_to_phone(i.phone_number, country_code: country_code(i.country), delimiter: " ")%></td>
            <td><%= i.city%></td>
            <td><%= i.country%></td>
            <td><%= emoji_flag_for_country(i.country) %></td>
            <td>$<%= i.cost%>/hour</td>
          </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>
  <%= button_to 'Join as a Guide', new_guide_path, :method => :get, :class => 'button is-primary'%>
</div>

app/views/reviews/new.html.erb
<h1 class="title"><%= "Review for #{@review.guide.name}"%></h1>
<%=form_with model: @review do |form|%>
    <%= form.hidden_field :guide_id%>
    <div class="field">
        <%=label(:comment, 'Comment', :class => 'label')%>
        <div class="control">
            <%= form.text_field :comment, required: true, minlength: 1, :class => 'input', :type => 'text', :placeholder => 'Enter your comment here'%>
        </div>
    </div>
    <br>
    <p><%= form.submit "Add review", :class => "button is-primary" %></p>
    <br>
    <p class="link item-link"><%= link_to 'Cancel', :back, :class => "button is-primary"%>
<%end%>

app/views/shared/_topnav.html.erb
<section>
    <% if user_signed_in? %>
        <div id="logout"><%= link_to 'Logout', destroy_user_session_path, method: "delete" %></div>
        <div id="username"><%= current_user.email %></div>
    <% else %>
        <p><%= link_to 'Login', new_user_session_path %>
|
        <%= link_to 'Sign Up', new_user_registration_path %>
        </p>
    <% end %>
</section>